/* The CPU twin of the Zstd literals section (src/zstd_literals.h): the four
 * block types, the size-format variants of the header, and the one- and
 * four-stream Huffman decodes (issue #221). The sibling of
 * tests/zstd_huf_twin.cpp and tests/zstd_seq_twin.cpp: the single-source unit
 * executed on the host, on the GPU-less CI runner, and held to the pinned
 * reference's verdicts.
 *
 * THREE PROOFS, AND THEY ARE DIFFERENT IN KIND.
 *
 * THE SWEEP TAKES ITS SECTIONS FROM REAL FRAMES. Every compressed block of
 * every #185 fixture is reached by walking the frame with the tree's own
 * src/zstd_frame.h, and the literals section it opens with is decoded here.
 * Two independent things are then asserted against it. The header fields are
 * compared with what tests/zstd_corpus.h's frame walker reports for the same
 * block, which is a second reader of the same bytes written for a different
 * purpose - so a shift that both this unit and its twin got wrong would still
 * have to have been got wrong a third time to pass. And for the two
 * compressed types the regenerated bytes are compared with the reference's
 * own HUF_decompress entry points, which is the byte-parity claim.
 *
 * THE REFERENCE'S TABLE IS CARRIED THE WAY THE REFERENCE CARRIES IT. A
 * Compressed section is decoded through the _DCtx_wksp entry points, which
 * read the tree description and leave the table in the caller's HUF_DTable; a
 * Treeless one through the _usingDTable entry points, which read no
 * description and use what is there. That is ZSTD_decodeLiteralsBlock's own
 * split between set_compressed and set_repeat, and mirroring it is what makes
 * the Treeless rows a test of the carry rather than of an accident.
 *
 * THE NEGATIVES ARE WHOLE FRAMES THE REFERENCE HAS TO REFUSE. A literals
 * section is not an entry point libzstd exposes, so a crafted section alone
 * has no reference verdict. Each negative is therefore wrapped in a minimal
 * frame - one compressed block, that literals section, zero sequences - and
 * ZSTD_decompress is asked for its opinion beside the twin's. The positive
 * control below proves the wrapper itself is a frame the reference accepts,
 * so a refusal in a negative is the mutation's and not the wrapper's. */
#include "require.h"
#include "zstd_corpus.h"
#include "zstd_literals.h"

/* The reference's Huffman entry points are internal to libzstd and its huf.h
 * carries no C++ linkage guard of its own, so the include is wrapped here
 * rather than its declarations restated. HUF_STATIC_LINKING_ONLY is what
 * exposes the four decompress entry points and the workspace macro; it is
 * defined by the build for the reason issue #180 landed, and defining it in
 * both places is a redefinition the strict-warning build refuses. */
extern "C" {
#include <common/huf.h>
}

#include <zstd.h>

#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

namespace {

using Bytes = std::vector<unsigned char>;

using cudec_detail::ZstdDecodeLiterals;
using cudec_detail::ZstdHufCell;
using cudec_detail::ZstdLiteralsHeader;
using cudec_detail::ZstdLiteralsReject;
using cudec_detail::ZstdLiteralsScratch;
using cudec_detail::ZstdLiteralsTable;
using cudec_detail::ZstdParseLiteralsHeader;

/* Which reject rungs a declared negative reached. Same discipline as the
 * Huffman, FSE and bitstream twins: the enumeration lives once, in the
 * header, and main() requires every rung to have been named by a negative
 * written to reach it. A rung added to the unit with no negative behind it
 * reds this test. */
bool g_reject_covered[cudec_detail::kZstdLiteralsRejectCount] = {false};

void CoverRung(ZstdLiteralsReject rung) {
    if (rung != cudec_detail::kZstdLiteralsRejectNone) {
        g_reject_covered[rung] = true;
    }
}

/* The window every hand-built frame below declares, and the block maximum it
 * implies: Window_Descriptor 0x38 is exponent 7, mantissa 0, so the window is
 * 2^17 and the block maximum is the 128 KB ceiling rather than the window. */
constexpr unsigned char kWindowDescriptor = 0x38;
constexpr uint64_t kWindowSize = 128ull * 1024ull;

/* Storage the unit asks the caller for, sized once here. The cell array is
 * the deepest literals tree the format admits. */
struct TwinState {
    std::vector<ZstdHufCell> cells;
    ZstdLiteralsScratch scratch;
    ZstdLiteralsTable table;

    TwinState()
        : cells(1u << cudec_detail::kZstdLiteralsMaxTableLog), scratch(),
          table() {
        table.cells = cells.data();
        table.capacity = static_cast<uint32_t>(cells.size());
        table.table_log = 0;
        table.present = false;
    }
};

/* One literals section located in a frame: where it starts and how many
 * bytes of its block body follow from there. */
struct LiteralsSite {
    size_t offset;
    size_t available;
    size_t block_index;
};

/* Walks a frame with the tree's own frame and block header units and reports
 * every compressed block's literals section. Deliberately not the corpus
 * walker: that one is the independent second reader this test compares
 * against, and using it here would collapse the two into one.
 *
 * Returns the frame unit's own status, so a caller can separate a frame this
 * decoder DECLINES from one it refuses. The #185 corpus carries envelope
 * fixtures deliberately outside the v1 subset - a frame with no declared
 * content size is the one that reaches here - and those are counted and
 * reported rather than passed over in silence. */
cudec_status WalkLiteralsSites(const Bytes& frame, uint64_t* window_size,
                               std::vector<LiteralsSite>* sites,
                               std::string* why) {
    cudec_detail::ZstdFrameHeader header;
    cudec_detail::ZstdFrameReject frame_reject;
    const cudec_status header_status = cudec_detail::ZstdParseFrameHeader(
        frame.data(), frame.size(), &header, &frame_reject);
    if (header_status != CUDEC_OK) {
        *why = "frame header refused";
        return header_status;
    }
    *window_size = header.window_size;
    uint64_t pos = header.header_size;
    size_t block_index = 0;
    for (;;) {
        cudec_detail::ZstdBlockHeader block;
        const cudec_status block_status = cudec_detail::ZstdParseBlockHeader(
            frame.data() + pos, frame.size() - pos, header.window_size, &block,
            &frame_reject);
        if (block_status != CUDEC_OK) {
            *why = "block header refused";
            return block_status;
        }
        if (block.block_type == cudec_detail::kZstdBlockTypeCompressed) {
            LiteralsSite site;
            site.offset = static_cast<size_t>(pos) + 3;
            site.available = block.body_size;
            site.block_index = block_index;
            sites->push_back(site);
        }
        pos += 3 + block.body_size;
        block_index++;
        if (block.last_block) {
            return CUDEC_OK;
        }
    }
}

/* A minimal frame around one literals section: no dictionary, no checksum, a
 * declared content size, an explicit window, and a single last compressed
 * block whose sequences section declares zero sequences. That last byte is
 * what makes the block's output the literals themselves, which is what gives
 * ZSTD_decompress an opinion on a literals section. */
Bytes BuildFrame(const Bytes& section, uint32_t content_size) {
    Bytes frame = {0x28, 0xb5, 0x2f, 0xfd, 0x80, kWindowDescriptor};
    for (unsigned i = 0; i < 4; i++) {
        frame.push_back(static_cast<unsigned char>(content_size >> (8u * i)));
    }
    Bytes body = section;
    body.push_back(0x00);
    const uint32_t block_header =
        static_cast<uint32_t>(body.size() << 3) | (2u << 1) | 1u;
    for (unsigned i = 0; i < 3; i++) {
        frame.push_back(static_cast<unsigned char>(block_header >> (8u * i)));
    }
    frame.insert(frame.end(), body.begin(), body.end());
    return frame;
}

bool ReferenceRefusesFrame(const Bytes& frame, size_t dst_capacity) {
    Bytes out(dst_capacity == 0 ? 1 : dst_capacity, 0);
    const size_t result =
        ZSTD_decompress(out.data(), dst_capacity, frame.data(), frame.size());
    return ZSTD_isError(result) != 0;
}

/* Sections lifted out of real frames during the sweep, so the negatives below
 * are mutations of bytes the reference itself accepts. Both are Compressed
 * rather than Treeless: a Treeless section carries no tree, so a negative
 * built from one would be testing the carry as well as the mutation. */
Bytes g_one_stream_section;
Bytes g_four_stream_section;
uint32_t g_one_stream_regenerated = 0;
uint32_t g_four_stream_regenerated = 0;

size_t g_sections = 0;
size_t g_literal_bytes = 0;
size_t g_type_seen[4] = {0, 0, 0, 0};
size_t g_four_stream_short_last = 0;
size_t g_outside_subset = 0;

/* One section from a real frame: decode it with the twin, cross-check the
 * header against the corpus walker's independent read, and, for the two
 * compressed types, diff the regenerated bytes against the reference. */
int SweepSection(const Bytes& frame, const LiteralsSite& site,
                 const ZstdBlockShape& shape, uint64_t window_size,
                 TwinState* state, HUF_DTable* ref_table, bool* ref_table_set,
                 const char* fixture) {
    const unsigned char* section = frame.data() + site.offset;

    ZstdLiteralsHeader header;
    ZstdLiteralsReject rung = cudec_detail::kZstdLiteralsRejectNone;
    REQUIRE_CTX(ZstdParseLiteralsHeader(section, site.available, &header,
                                        &rung) == CUDEC_OK,
                "%s: literals header refused", fixture);
    REQUIRE_CTX(header.block_type == shape.literals_type,
                "%s: type %u, walker says %u", fixture, header.block_type,
                shape.literals_type);
    REQUIRE_CTX(header.stream_count == shape.literals_streams,
                "%s: %u streams, walker says %u", fixture, header.stream_count,
                shape.literals_streams);

    const bool compressed =
        header.block_type == cudec_detail::kZstdLiteralsTypeCompressed ||
        header.block_type == cudec_detail::kZstdLiteralsTypeTreeless;
    if (compressed) {
        REQUIRE_CTX(site.offset + header.header_size ==
                        shape.literals_payload_offset,
                    "%s: payload at %zu, walker says %zu", fixture,
                    site.offset + header.header_size,
                    shape.literals_payload_offset);
        REQUIRE_CTX(header.compressed_size == shape.literals_payload_size,
                    "%s: compressed size %llu, walker says %zu", fixture,
                    static_cast<unsigned long long>(header.compressed_size),
                    shape.literals_payload_size);
    }

    Bytes twin(header.regenerated_size == 0 ? 1 : header.regenerated_size, 0);
    uint64_t produced = 0;
    uint64_t consumed = 0;
    REQUIRE_CTX(ZstdDecodeLiterals(section, site.available, window_size,
                                   &state->table, &state->scratch, twin.data(),
                                   twin.size(), &produced, &consumed,
                                   &rung) == CUDEC_OK,
                "%s: literals decode refused at rung %d", fixture,
                static_cast<int>(rung));
    REQUIRE_CTX(produced == header.regenerated_size, "%s: produced %llu",
                fixture, static_cast<unsigned long long>(produced));
    REQUIRE_CTX(consumed <= site.available, "%s: consumed past the block",
                fixture);

    g_sections++;
    g_type_seen[header.block_type]++;
    g_literal_bytes += static_cast<size_t>(produced);

    if (!compressed) {
        /* Raw and RLE put nothing through the reference's Huffman decoder, so
         * what these rows prove is the type dispatch, the header widths and
         * the bounds gate - which is exactly what the cross-check above
         * asserts. The bytes are checked against the section itself. */
        const unsigned char* content = section + header.header_size;
        for (uint64_t i = 0; i < produced; i++) {
            const unsigned char want =
                header.block_type == cudec_detail::kZstdLiteralsTypeRaw
                    ? content[i]
                    : content[0];
            REQUIRE_CTX(twin[i] == want, "%s: byte %llu", fixture,
                        static_cast<unsigned long long>(i));
        }
        return 0;
    }

    const unsigned char* payload = section + header.header_size;
    const size_t payload_size = static_cast<size_t>(header.compressed_size);
    Bytes reference(twin.size(), 0);
    std::vector<uint32_t> workspace(HUF_DECOMPRESS_WORKSPACE_SIZE_U32, 0);
    size_t result = 0;
    if (header.block_type == cudec_detail::kZstdLiteralsTypeCompressed) {
        result = header.stream_count == 1
                     ? HUF_decompress1X1_DCtx_wksp(
                           ref_table, reference.data(),
                           static_cast<size_t>(produced), payload,
                           payload_size, workspace.data(),
                           workspace.size() * sizeof(uint32_t), 0)
                     : HUF_decompress4X_hufOnly_wksp(
                           ref_table, reference.data(),
                           static_cast<size_t>(produced), payload,
                           payload_size, workspace.data(),
                           workspace.size() * sizeof(uint32_t), 0);
        *ref_table_set = true;
    } else {
        REQUIRE_CTX(*ref_table_set, "%s: treeless with no reference table",
                    fixture);
        result = header.stream_count == 1
                     ? HUF_decompress1X_usingDTable(
                           reference.data(), static_cast<size_t>(produced),
                           payload, payload_size, ref_table, 0)
                     : HUF_decompress4X_usingDTable(
                           reference.data(), static_cast<size_t>(produced),
                           payload, payload_size, ref_table, 0);
    }
    REQUIRE_CTX(!HUF_isError(result), "%s: reference refused the section",
                fixture);
    REQUIRE_CTX(result == produced, "%s: reference produced %zu, twin %llu",
                fixture, result, static_cast<unsigned long long>(produced));
    REQUIRE_CTX(equal_bytes(twin.data(), reference.data(),
                            static_cast<size_t>(produced)),
                "%s: literals differ from the reference", fixture);

    if (header.stream_count == cudec_detail::kZstdLiteralsStreamCount) {
        if (header.regenerated_size % 4 != 0) {
            g_four_stream_short_last++;
        }
        if (g_four_stream_section.empty() &&
            header.block_type ==
                cudec_detail::kZstdLiteralsTypeCompressed &&
            header.compressed_size >= 32) {
            g_four_stream_section.assign(
                section, section + header.header_size + payload_size);
            g_four_stream_regenerated =
                static_cast<uint32_t>(header.regenerated_size);
        }
    } else if (g_one_stream_section.empty() &&
               header.block_type ==
                   cudec_detail::kZstdLiteralsTypeCompressed) {
        g_one_stream_section.assign(section,
                                    section + header.header_size +
                                        payload_size);
        g_one_stream_regenerated =
            static_cast<uint32_t>(header.regenerated_size);
    }
    return 0;
}

int Sweep() {
    const std::vector<ZstdFixture> fixtures = MakeZstdFixtures();
    REQUIRE(!fixtures.empty());
    for (const ZstdFixture& fixture : fixtures) {
        ZstdFrameShape shape;
        std::string why;
        REQUIRE_CTX(ParseZstdFrameShape(fixture.compressed, &shape, &why),
                    "%s: %s", fixture.name.c_str(), why.c_str());

        uint64_t window_size = 0;
        std::vector<LiteralsSite> sites;
        const cudec_status walk =
            WalkLiteralsSites(fixture.compressed, &window_size, &sites, &why);
        if (walk == CUDEC_ERR_UNSUPPORTED) {
            /* A legal frame outside the v1 subset. Counted and named in the
             * PASS line: a fixture that fell out of the sweep by accident
             * must not read like one that was swept. */
            g_outside_subset++;
            continue;
        }
        REQUIRE_CTX(walk == CUDEC_OK, "%s: %s", fixture.name.c_str(),
                    why.c_str());

        TwinState state;
        HUF_CREATE_STATIC_DTABLEX1(ref_table, HUF_TABLELOG_MAX);
        bool ref_table_set = false;
        for (const LiteralsSite& site : sites) {
            REQUIRE_CTX(site.block_index < shape.blocks.size(),
                        "%s: block %zu past the walker's list",
                        fixture.name.c_str(), site.block_index);
            const int rc = SweepSection(
                fixture.compressed, site, shape.blocks[site.block_index],
                window_size, &state, ref_table, &ref_table_set,
                fixture.name.c_str());
            if (rc != 0) {
                return rc;
            }
        }
    }
    return 0;
}

/* Wraps one literals section in the minimal frame and sweeps it exactly as a
 * corpus frame is swept, with the reference's whole-frame verdict asserted
 * first.
 *
 * This is what carries the two trivial types AND the wrapper's own positive
 * control in one row. The #185 corpus does contain an RLE literals section,
 * in a hand-built frame that declares no content size - a legal frame outside
 * the v1 subset this decoder implements - so the sweep above declines that
 * frame before it ever reaches the section. Re-wrapping the same section here
 * is what puts the RLE arm of the dispatch under the sweep's assertions
 * rather than leaving it uncovered. */
int SweepBuiltFrame(const Bytes& section, uint32_t content_size,
                    const Bytes& expected, const char* name) {
    const Bytes frame = BuildFrame(section, content_size);
    Bytes out(content_size == 0 ? 1 : content_size, 0);
    const size_t result =
        ZSTD_decompress(out.data(), content_size, frame.data(), frame.size());
    REQUIRE_CTX(!ZSTD_isError(result), "%s: the reference refused the wrapper",
                name);
    REQUIRE_CTX(result == content_size, "%s: the reference produced %zu", name,
                result);
    REQUIRE_CTX(equal_bytes(out.data(), expected.data(), content_size),
                "%s: the reference decoded other bytes", name);

    ZstdFrameShape shape;
    std::string why;
    REQUIRE_CTX(ParseZstdFrameShape(frame, &shape, &why), "%s: %s", name,
                why.c_str());
    uint64_t window_size = 0;
    std::vector<LiteralsSite> sites;
    REQUIRE_CTX(
        WalkLiteralsSites(frame, &window_size, &sites, &why) == CUDEC_OK,
        "%s: %s", name, why.c_str());
    REQUIRE_CTX(sites.size() == 1, "%s: %zu literals sections", name,
                sites.size());

    TwinState state;
    HUF_CREATE_STATIC_DTABLEX1(ref_table, HUF_TABLELOG_MAX);
    bool ref_table_set = false;
    return SweepSection(frame, sites[0], shape.blocks[sites[0].block_index],
                        window_size, &state, ref_table, &ref_table_set, name);
}

/* A section whose Regenerated_Size is not a multiple of four, so the short
 * fourth segment is exercised and not merely assumed.
 *
 * Searched for rather than hand-written: the four-stream split is the
 * compressor's decision and a section this file wrote would not be one the
 * compressor emits. The search is over deterministic inputs of ascending
 * length, so the fixture it finds is the same one on every run, and it fails
 * rather than skips when nothing is found. */
int RequireShortLastSegment() {
    if (g_four_stream_short_last > 0) {
        return 0;
    }
    for (size_t length = 2048; length <= 8192; length++) {
        Bytes source(length, 0);
        uint32_t state = 0x12345678u;
        for (size_t i = 0; i < length; i++) {
            state = state * 1664525u + 1013904223u;
            /* A small, skewed alphabet: enough repetition for the compressor
             * to reach for a Huffman tree, enough symbols for a real one. */
            source[i] = static_cast<unsigned char>((state >> 24) % 24u + 'a');
        }
        Bytes frame(ZSTD_compressBound(length), 0);
        const size_t written = ZSTD_compress(frame.data(), frame.size(),
                                             source.data(), length, 3);
        REQUIRE(!ZSTD_isError(written));
        frame.resize(written);

        ZstdFrameShape shape;
        std::string why;
        if (!ParseZstdFrameShape(frame, &shape, &why)) {
            continue;
        }
        uint64_t window_size = 0;
        std::vector<LiteralsSite> sites;
        if (WalkLiteralsSites(frame, &window_size, &sites, &why) !=
            CUDEC_OK) {
            continue;
        }
        TwinState state_twin;
        HUF_CREATE_STATIC_DTABLEX1(ref_table, HUF_TABLELOG_MAX);
        bool ref_table_set = false;
        bool found = false;
        for (const LiteralsSite& site : sites) {
            ZstdLiteralsHeader header;
            ZstdLiteralsReject rung = cudec_detail::kZstdLiteralsRejectNone;
            if (ZstdParseLiteralsHeader(frame.data() + site.offset,
                                        site.available, &header,
                                        &rung) != CUDEC_OK) {
                break;
            }
            if (header.stream_count ==
                    cudec_detail::kZstdLiteralsStreamCount &&
                header.regenerated_size % 4 != 0) {
                found = true;
            }
        }
        if (!found) {
            continue;
        }
        for (const LiteralsSite& site : sites) {
            REQUIRE(site.block_index < shape.blocks.size());
            const int rc =
                SweepSection(frame, site, shape.blocks[site.block_index],
                             window_size, &state_twin, ref_table,
                             &ref_table_set, "short-last-segment");
            if (rc != 0) {
                return rc;
            }
        }
        REQUIRE(g_four_stream_short_last > 0);
        return 0;
    }
    /* No skip: a fixture that reaches the short fourth segment is what this
     * clause of the issue asks for, and not finding one is a failure of this
     * search rather than a property the format lacks. */
    REQUIRE(g_four_stream_short_last > 0);
    return 0;
}

/* Decodes `section` with the twin and requires the declared rung, and
 * requires the reference to refuse the frame the same section is wrapped in.
 * `content_size` is what the wrapper declares; the reference refuses either
 * way, and declaring the section's own regenerated size keeps the refusal
 * about the mutation. */
int Negative(const char* what, const Bytes& section, uint32_t content_size,
             uint64_t window_size, TwinState* state, size_t dst_capacity,
             ZstdLiteralsReject want_rung, cudec_status want_status) {
    Bytes dst(dst_capacity == 0 ? 1 : dst_capacity, 0);
    uint64_t produced = 0;
    uint64_t consumed = 0;
    ZstdLiteralsReject rung = cudec_detail::kZstdLiteralsRejectNone;
    const cudec_status status = ZstdDecodeLiterals(
        section.data(), section.size(), window_size, &state->table,
        &state->scratch, dst.data(), dst_capacity, &produced, &consumed,
        &rung);
    REQUIRE_CTX(status == want_status, "%s: status %d", what,
                static_cast<int>(status));
    REQUIRE_CTX(rung == want_rung, "%s: rung %d", what,
                static_cast<int>(rung));
    REQUIRE_CTX(produced == 0, "%s: produced %llu on a refusal", what,
                static_cast<unsigned long long>(produced));
    REQUIRE_CTX(
        ReferenceRefusesFrame(BuildFrame(section, content_size), dst_capacity),
        "%s: the reference accepted it", what);
    CoverRung(rung);
    return 0;
}

/* The two sizes in a Compressed/Treeless header, rewritten in place. Only the
 * three-byte spelling is written here, which is the one every section lifted
 * out of the corpus uses at these block sizes; a section in another spelling
 * would make the negatives below silently edit the wrong bits, so the caller
 * asserts the spelling first. */
void RewriteCompressedHeader(Bytes* section, uint32_t regenerated,
                             uint32_t compressed) {
    const uint32_t low = (*section)[0] & 0x0fu;
    const uint32_t packed =
        low | (regenerated << 4) | (compressed << 14);
    for (unsigned i = 0; i < 3; i++) {
        (*section)[i] = static_cast<unsigned char>(packed >> (8u * i));
    }
}

/* The Raw and RLE arms, and with them the proof that the wrapper used by
 * every negative below is a frame the reference accepts. */
int WrappedPositives() {
    {
        Bytes section;
        section.push_back(static_cast<unsigned char>(
            cudec_detail::kZstdLiteralsTypeRaw | (16u << 3)));
        Bytes expected;
        for (unsigned i = 0; i < 16; i++) {
            expected.push_back(static_cast<unsigned char>('a' + i));
        }
        section.insert(section.end(), expected.begin(), expected.end());
        const int rc = SweepBuiltFrame(section, 16, expected, "raw-wrapped");
        if (rc != 0) {
            return rc;
        }
    }
    {
        /* The same section the corpus's hand-built RLE fixture carries:
         * Size_Format 00, Regenerated_Size 20, one repeated byte. */
        Bytes section;
        section.push_back(static_cast<unsigned char>(
            cudec_detail::kZstdLiteralsTypeRle | (20u << 3)));
        section.push_back('z');
        const Bytes expected(20, 'z');
        const int rc = SweepBuiltFrame(section, 20, expected, "rle-wrapped");
        if (rc != 0) {
            return rc;
        }
    }
    return 0;
}

/* Where a lifted section's tree description ends, which is where its streams
 * (and, in the four-stream shape, its jump table) begin. Read with the unit's
 * own Huffman entry point rather than recomputed here: the negatives below
 * cut the payload at that boundary, and a boundary this file derived
 * separately would be a second implementation to get wrong. */
int SectionDescriptionSize(const Bytes& section, size_t* header_size,
                           uint64_t* description_size) {
    ZstdLiteralsHeader header;
    ZstdLiteralsReject rung = cudec_detail::kZstdLiteralsRejectNone;
    REQUIRE(ZstdParseLiteralsHeader(section.data(), section.size(), &header,
                                    &rung) == CUDEC_OK);
    ZstdLiteralsScratch scratch;
    uint8_t weights[cudec_detail::kZstdHufMaxSymbolValue + 1];
    unsigned symbol_count = 0;
    unsigned table_log = 0;
    cudec_detail::ZstdHufReject huf_rung = cudec_detail::kZstdHufRejectNone;
    REQUIRE(cudec_detail::ZstdHufReadWeights(
                section.data() + header.header_size,
                section.size() - header.header_size,
                cudec_detail::kZstdHufMaxSymbolValue + 1,
                cudec_detail::kZstdLiteralsMaxTableLog,
                &scratch.weights_scratch, weights, &symbol_count, &table_log,
                description_size, &huf_rung) == CUDEC_OK);
    *header_size = header.header_size;
    return 0;
}

int Negatives() {
    REQUIRE(!g_one_stream_section.empty());
    REQUIRE(!g_four_stream_section.empty());
    /* Both were lifted from real frames; the rewrites below assume the
     * three-byte header spelling, which is size format 0 or 1. */
    REQUIRE(((g_one_stream_section[0] >> 2) & 0x3u) == 0);
    REQUIRE(((g_four_stream_section[0] >> 2) & 0x3u) == 1);

    TwinState state;

    /* A caller that hands over storage smaller than the deepest literals tree
     * the format admits. Not a stream: refused as an argument, and the
     * reference has no opinion because there is no such call to make. */
    {
        TwinState small;
        small.table.capacity = 4;
        uint64_t produced = 0;
        uint64_t consumed = 0;
        ZstdLiteralsReject rung = cudec_detail::kZstdLiteralsRejectNone;
        Bytes dst(64, 0);
        REQUIRE(ZstdDecodeLiterals(g_one_stream_section.data(),
                                   g_one_stream_section.size(), kWindowSize,
                                   &small.table, &small.scratch, dst.data(),
                                   dst.size(), &produced, &consumed,
                                   &rung) == CUDEC_ERR_INVALID_ARGUMENT);
        REQUIRE(rung == cudec_detail::kZstdLiteralsRejectBadRequest);
        CoverRung(rung);
    }

    /* A Treeless section over a table marked present at a depth this unit
     * could not have written. The cell array is the bound the stream decode
     * indexes by, so a stale depth is refused as an argument rather than
     * trusted one call deeper. */
    {
        TwinState stale;
        stale.table.present = true;
        stale.table.table_log = cudec_detail::kZstdLiteralsMaxTableLog + 1;
        Bytes section = g_one_stream_section;
        section[0] = static_cast<unsigned char>(
            (section[0] & ~0x03u) | cudec_detail::kZstdLiteralsTypeTreeless);
        uint64_t produced = 0;
        uint64_t consumed = 0;
        ZstdLiteralsReject rung = cudec_detail::kZstdLiteralsRejectNone;
        Bytes dst(g_one_stream_regenerated, 0);
        REQUIRE(ZstdDecodeLiterals(section.data(), section.size(), kWindowSize,
                                   &stale.table, &stale.scratch, dst.data(),
                                   dst.size(), &produced, &consumed,
                                   &rung) == CUDEC_ERR_INVALID_ARGUMENT);
        REQUIRE(rung == cudec_detail::kZstdLiteralsRejectBadRequest);
        CoverRung(rung);
    }

    /* A header that ends before its own size format does: a Compressed
     * section in the five-byte spelling, one byte long. */
    {
        Bytes section;
        section.push_back(static_cast<unsigned char>(
            cudec_detail::kZstdLiteralsTypeCompressed | (3u << 2)));
        const int rc =
            Negative("header truncated", section, 1, kWindowSize, &state, 64,
                     cudec_detail::kZstdLiteralsRejectHeaderTruncated,
                     CUDEC_ERR_CORRUPT_INPUT);
        if (rc != 0) {
            return rc;
        }
    }

    /* Regenerated_Size past the block maximum. The five-byte spelling is the
     * only one whose field is wide enough to say it. */
    {
        Bytes section;
        const uint64_t regenerated = kWindowSize + 1;
        const uint64_t packed =
            static_cast<uint64_t>(cudec_detail::kZstdLiteralsTypeCompressed) |
            (3ull << 2) | (regenerated << 4) | (16ull << 22);
        for (unsigned i = 0; i < 5; i++) {
            section.push_back(static_cast<unsigned char>(packed >> (8u * i)));
        }
        section.resize(section.size() + 16, 0);
        const int rc = Negative(
            "regenerated past the block maximum", section, 64, kWindowSize,
            &state, 1 << 20,
            cudec_detail::kZstdLiteralsRejectRegeneratedTooLarge,
            CUDEC_ERR_CORRUPT_INPUT);
        if (rc != 0) {
            return rc;
        }
    }

    /* The same field against a window BELOW the ceiling, which is the other
     * side of the same bound: the block maximum is the smaller of the two,
     * and a decoder that only compared against 128 KB would accept this. */
    {
        Bytes section;
        section.push_back(static_cast<unsigned char>(
            cudec_detail::kZstdLiteralsTypeRaw | (1u << 2)));
        section.push_back(0x40); /* 12-bit regenerated size: 0x400 */
        section.resize(section.size() + 0x400, 0);
        uint64_t produced = 0;
        uint64_t consumed = 0;
        ZstdLiteralsReject rung = cudec_detail::kZstdLiteralsRejectNone;
        Bytes dst(0x400, 0);
        REQUIRE(ZstdDecodeLiterals(section.data(), section.size(), 0x100,
                                   &state.table, &state.scratch, dst.data(),
                                   dst.size(), &produced, &consumed,
                                   &rung) == CUDEC_ERR_CORRUPT_INPUT);
        REQUIRE(rung ==
                cudec_detail::kZstdLiteralsRejectRegeneratedTooLarge);
        CoverRung(rung);
    }

    /* Regenerated_Size past the destination the caller supplied. The one rung
     * the reference also keeps out of its corruption class, so the wrapper is
     * decompressed into a destination of the same size and refused there. */
    {
        Bytes section = g_one_stream_section;
        const int rc =
            Negative("regenerated past capacity", section,
                     g_one_stream_regenerated, kWindowSize, &state,
                     g_one_stream_regenerated - 1,
                     cudec_detail::kZstdLiteralsRejectRegeneratedPastCapacity,
                     CUDEC_ERR_OUTPUT_TOO_SMALL);
        if (rc != 0) {
            return rc;
        }
    }

    /* A Raw section whose literals are not all there. Twenty declared in the
     * one-byte spelling, whose Regenerated_Size field is five bits wide, and
     * eight present. */
    {
        Bytes section;
        section.push_back(static_cast<unsigned char>(
            cudec_detail::kZstdLiteralsTypeRaw | (20u << 3)));
        section.resize(section.size() + 8, 'x');
        const int rc =
            Negative("raw literals truncated", section, 20, kWindowSize,
                     &state, 64,
                     cudec_detail::kZstdLiteralsRejectContentTruncated,
                     CUDEC_ERR_CORRUPT_INPUT);
        if (rc != 0) {
            return rc;
        }
    }

    /* An RLE section without the one byte it repeats. */
    {
        Bytes section;
        section.push_back(static_cast<unsigned char>(
            cudec_detail::kZstdLiteralsTypeRle | (20u << 3)));
        const int rc =
            Negative("rle symbol absent", section, 20, kWindowSize, &state, 64,
                     cudec_detail::kZstdLiteralsRejectContentTruncated,
                     CUDEC_ERR_CORRUPT_INPUT);
        if (rc != 0) {
            return rc;
        }
    }

    /* Compressed_Size reaching past the bytes the section has. */
    {
        Bytes section = g_one_stream_section;
        RewriteCompressedHeader(&section, g_one_stream_regenerated,
                                static_cast<uint32_t>(section.size()) + 16u);
        const int rc =
            Negative("compressed payload truncated", section,
                     g_one_stream_regenerated, kWindowSize, &state, 1 << 17,
                     cudec_detail::kZstdLiteralsRejectPayloadTruncated,
                     CUDEC_ERR_CORRUPT_INPUT);
        if (rc != 0) {
            return rc;
        }
    }

    /* A Treeless section with no table behind it. The state is fresh, which
     * is the first block of a frame. */
    {
        TwinState fresh;
        Bytes section = g_one_stream_section;
        section[0] = static_cast<unsigned char>(
            (section[0] & ~0x03u) | cudec_detail::kZstdLiteralsTypeTreeless);
        const int rc =
            Negative("treeless with no previous table", section,
                     g_one_stream_regenerated, kWindowSize, &fresh, 1 << 17,
                     cudec_detail::kZstdLiteralsRejectNoPreviousTable,
                     CUDEC_ERR_CORRUPT_INPUT);
        if (rc != 0) {
            return rc;
        }
    }

    /* A tree description that describes no tree: the header byte says a
     * compressed description of zero bytes follows. */
    {
        Bytes section = g_one_stream_section;
        const size_t header_size = 3;
        section[header_size] = 0x00;
        const int rc =
            Negative("tree description refused", section,
                     g_one_stream_regenerated, kWindowSize, &state, 1 << 17,
                     cudec_detail::kZstdLiteralsRejectTreeDescription,
                     CUDEC_ERR_CORRUPT_INPUT);
        if (rc != 0) {
            return rc;
        }
    }

    /* A payload that is nothing but its tree description, leaving no stream
     * for the literals to come out of. */
    {
        Bytes section = g_one_stream_section;
        size_t header_size = 0;
        uint64_t description_size = 0;
        const int read =
            SectionDescriptionSize(section, &header_size, &description_size);
        if (read != 0) {
            return read;
        }
        section.resize(header_size + description_size);
        RewriteCompressedHeader(&section, g_one_stream_regenerated,
                                static_cast<uint32_t>(description_size));
        const int rc =
            Negative("streams absent", section, g_one_stream_regenerated,
                     kWindowSize, &state, 1 << 17,
                     cudec_detail::kZstdLiteralsRejectStreamsAbsent,
                     CUDEC_ERR_CORRUPT_INPUT);
        if (rc != 0) {
            return rc;
        }
    }

    /* A four-stream payload that holds a whole tree description and then
     * fewer bytes than a jump table plus one per stream. The description is
     * left intact on purpose: cutting into it would be refused one rung
     * earlier and this rung would never be reached. */
    {
        Bytes section = g_four_stream_section;
        size_t header_size = 0;
        uint64_t description_size = 0;
        const int read =
            SectionDescriptionSize(section, &header_size, &description_size);
        if (read != 0) {
            return read;
        }
        const uint64_t payload = description_size + 9;
        section.resize(header_size + payload);
        RewriteCompressedHeader(&section, g_four_stream_regenerated,
                                static_cast<uint32_t>(payload));
        const int rc = Negative(
            "four-stream payload too short", section,
            g_four_stream_regenerated, kWindowSize, &state, 1 << 17,
            cudec_detail::kZstdLiteralsRejectFourStreamPayloadTooShort,
            CUDEC_ERR_CORRUPT_INPUT);
        if (rc != 0) {
            return rc;
        }
    }

    /* A four-stream section with fewer literals than the split needs. */
    {
        Bytes section = g_four_stream_section;
        RewriteCompressedHeader(
            &section, 5,
            static_cast<uint32_t>(section.size()) - 3u);
        const int rc = Negative(
            "four-stream too few literals", section, 5, kWindowSize, &state,
            1 << 17,
            cudec_detail::kZstdLiteralsRejectFourStreamTooFewLiterals,
            CUDEC_ERR_CORRUPT_INPUT);
        if (rc != 0) {
            return rc;
        }
    }

    /* A jump table whose declared sizes leave the fourth stream nothing. The
     * first entry alone is made to span the whole payload. */
    {
        Bytes section = g_four_stream_section;
        size_t header_size = 0;
        uint64_t description_size = 0;
        const int read =
            SectionDescriptionSize(section, &header_size, &description_size);
        if (read != 0) {
            return read;
        }
        /* The jump table sits after the tree description, and the four
         * streams follow it. Its first entry is the two bytes there. */
        const size_t jump =
            header_size + static_cast<size_t>(description_size);
        section[jump] = 0xff;
        section[jump + 1] = 0xff;
        const int rc = Negative(
            "jump table overruns", section, g_four_stream_regenerated,
            kWindowSize, &state, 1 << 17,
            cudec_detail::kZstdLiteralsRejectJumpTableOverruns,
            CUDEC_ERR_CORRUPT_INPUT);
        if (rc != 0) {
            return rc;
        }
    }

    /* A stream whose last byte carries no start marker, so where its data
     * begins is undefined. */
    {
        Bytes section = g_one_stream_section;
        section[section.size() - 1] = 0x00;
        const int rc =
            Negative("stream has no start marker", section,
                     g_one_stream_regenerated, kWindowSize, &state, 1 << 17,
                     cudec_detail::kZstdLiteralsRejectStreamTruncated,
                     CUDEC_ERR_CORRUPT_INPUT);
        if (rc != 0) {
            return rc;
        }
    }

    /* A section declaring fewer literals than its stream spells, so bits are
     * left when the last one is out. That is the fail-open the reference
     * refuses with its own end-of-stream check. */
    {
        Bytes section = g_one_stream_section;
        RewriteCompressedHeader(&section, g_one_stream_regenerated - 1,
                                static_cast<uint32_t>(section.size()) - 3u);
        const int rc =
            Negative("stream not consumed", section,
                     g_one_stream_regenerated - 1, kWindowSize, &state,
                     1 << 17,
                     cudec_detail::kZstdLiteralsRejectStreamNotConsumed,
                     CUDEC_ERR_CORRUPT_INPUT);
        if (rc != 0) {
            return rc;
        }
    }
    return 0;
}

}  // namespace

int main() {
    int rc = Sweep();
    if (rc != 0) {
        return rc;
    }
    rc = RequireShortLastSegment();
    if (rc != 0) {
        return rc;
    }
    rc = WrappedPositives();
    if (rc != 0) {
        return rc;
    }
    rc = Negatives();
    if (rc != 0) {
        return rc;
    }

    /* Every literals type was reached by the sweep. A corpus that stopped
     * emitting one of them would otherwise leave this test green over three
     * quarters of the dispatch. */
    for (unsigned type = 0; type < 4; type++) {
        REQUIRE_CTX(g_type_seen[type] > 0, "literals type %u never reached",
                    type);
    }

    /* Every rung the unit can return has a negative written to reach it. A
     * rung added later with nothing behind it reds here rather than shipping
     * as untested refusal. */
    for (int rung = cudec_detail::kZstdLiteralsRejectNone + 1;
         rung < cudec_detail::kZstdLiteralsRejectCount; rung++) {
        REQUIRE_CTX(g_reject_covered[rung], "reject rung %d has no negative",
                    rung);
    }

    std::printf("PASS: %zu literals sections decoded (%zu raw, %zu rle, %zu "
                "compressed, %zu treeless), %zu literal bytes diffed against "
                "HUF_decompress, %zu four-stream sections with a short last "
                "segment, %d reject rungs covered; %zu corpus frames left "
                "unswept as outside the v1 subset\n",
                g_sections, g_type_seen[0], g_type_seen[1], g_type_seen[2],
                g_type_seen[3], g_literal_bytes, g_four_stream_short_last,
                cudec_detail::kZstdLiteralsRejectCount - 1, g_outside_subset);
    return 0;
}
